### ISSUE TITLE
EMAIL (ID86)

### ISSUE THREAD

**Issue by GW-BIKE** [manuelhartl/odenwald-sports#17]
Durch Verwendung der Endung gmail oder googlemail kann ich mich mit gleicher Mailadresse 2x registrieren. ist sicher ein Sonderfall bei Google, aber sollte man mal klären, ob das so bleiben soll

Janine, ID86)

**Comment by GW-BIKE** [comment]
sollte diskutiert werden (Manuel, was meinst Du?)

**Comment by manuelhartl** [comment]
ich finde das ok. wir koennen sowieso nicht sicherstellen ob sich jemand zweimal anmeldet oder wieviele domains ein email provider hat
