### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by GW-BIKE** [manuelhartl/odenwald-sports#2]
Klick auf "PW vergessen", komme ich auf die Startseite (liegt vielleicht daran, dass ich keinen User hatte - soll das so sein oder vielleicht dann eher über Nachricht "zu dieser Emailadresse liegt uns kein bekannter User vor")

von Janine, ID53

**Comment by manuelhartl** [comment]
das ist ein fehler - schon gefixt
